members/urls.py
from django.urls import path
from .import views
app_name = "members"

urlpatterns = [
 
    path('', views.index,name='index'),
    path('home/', views.home,name='home'),
    path('blogpost/',views.blogpost, name='blogpost'),
    path('displayblogpost/',views.displayblogpost, name='displayblogpost'),
    path('signup/',views.signup, name='signup'),
    path('login/',views.login, name='login'),
    path('authordetail/',views.author, name='authordetail'),
]     

myworld/urls.py
from django.contrib import admin
from django.urls import include,path
#import members.views
#from myworld import members

urlpatterns = [
    path('members/',include('members.urls')),
    path('admin/', admin.site.urls),
    #path('',members.views.login, name='login'),
]

members/models.py
from dataclasses import field
from django.db import models
from django.utils import timezone


class User(models.Model): 
    User_name = models.CharField(max_length=50)
    User_mail = models.CharField(max_length=50)
    User_pwd = models.CharField(max_length=50)
    User_pno = models.BigIntegerField()
   

    def __str__(self):
        return self.User_name   

class Blog(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    Blogpost_name = models.CharField(max_length=50)
    Post_date = models.DateTimeField("date created",default=timezone.now())
    Content = models.CharField(max_length=100)
 
    def __str__(self):
        return self.Blogpost_name


    

# class Comment(models.Model):

#     User = models.ForeignKey(User, on_delete=models.CASCADE)
#     Blogpost_name = models.CharField(max_length=50)
#     Content = models.CharField(max_length=50)
    
#     def __str__(self) -> str:
#         return self.Author_id



     

members/forms.py
from django.forms import ModelForm
#from django.db import models
from .models import Blog, User

class Blogpostform(ModelForm):
    class Meta:
        model = Blog
        fields = ["Blogpost_name","User"]

class signupform(ModelForm):
    class Meta:
        model = User
        fields = ["User_name","User_mail","User_pwd","User_pno"] 

                 

members/views.py
from multiprocessing import context
from re import template
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.core.paginator import Paginator
from .models import Blog
from .forms import Blogpostform
from .forms import signupform
from members.models import Blog,User

def index(request):
    template = loader.get_template("index.html")
    return render(request,"index.html")

def home(request):
    template = loader.get_template('home.html')
    return render(request,"home.html") 

def blogpost(request):
    
    form = Blogpostform 
    print(form,"-")
    print(request.method)
    if 'save' in request.POST:
      
        data = Blogpostform(request.POST,request.FILES)
        print(data)
        if data.is_valid():
            data.save()
            return redirect('/members/displayblogpost')
    return render(request,'blogpost.html',{'form':form})  

def displayblogpost(request):
   mymembers = Blog.objects.all().order_by('-Post_date')
   
   paginator = Paginator(mymembers, 5) # Show 5 contacts per page.
   page_number = request.GET.get('page')
   mymembers = paginator.get_page(page_number)

   context = {
       'mymembers' : mymembers,
   } 
   return render(request,"displayblogpost.html",context)   
    

def signup(request):
    form = signupform
    if 'save' in request.POST:
        data = signupform(request.POST,request.FILES)
        if data.is_valid():
            data.save()
            return redirect('/members/')
    return render(request,'signup.html',{'form':form})    

def login(request):
    message =''
    if (request.method == 'GET'):
        return render(request, 'login.html')
    else:
        User_name = request.POST['User_name']
        User_pwd = request.POST['User_pwd']
        data = User.objects.all().filter(User_name=User_name,User_pwd=User_pwd)
        print(User_name,"-----------------------")
        print(User_pwd)
        for x in data:
            if x.User_name == User_name and x.User_pwd == User_pwd:
                print(User_name)
                print(User_pwd)
                print("Successfully inserted.............")
                return render(request, "index.html")
            # else:
            #     return render(request, "login.html")
            #     message = "Invalid login!"
            # #     return render(request, "login.html",context={'message':message})
       
def author(request):
    mymembers = User.objects.all()
    context = {
        'mymembers' : mymembers,
    }
    
    return render(request,"authordetail.html",context)     
      

members/templates/authordetail.html
<!DOCTYPE html>
<html>
    <head>
        <body>
            <form  method="POST" action="{% url 'members:authordetail' %}"> 
                <table>
                    <tr align="center">
                        <th>Id</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Password</th>
                        <th>Phonenumber</th>
                    </tr>
                    {% for x in mymembers %}
                    <tr align="center">
                        <td>{{ x.id }}</td>
                        <td>{{ x.User_name }}</td>
                        <td>{{ x.User_mail }}</td>
                        <td>{{ x.User_pwd }}</td>
                        <td>{{ x.User_pno }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </form>
        </body>
    </head>
</html>

members/templates/blogpost.html
<!DOCTYPE html>
<html>
<head>
<body>
    <form action ="{% url 'members:blogpost' %}" method="POST" enctype="multipart/form-data">
        <fieldset>
            <legend>Form</legend>
            {% csrf_token %}
            <table>{{ form }}</table>
            <input type="submit" value="View BlogPost List" name="save">
        </fieldset>
    </form>

</body>    
</head>    
</html>

members/templates/displayblogpost.html
<!DOCTYPE html>
<html>
<head>
<body>
<h1>Successfully inserted</h1>
<form>
<table border="1" width="25%">
    <tr>
        <th>Author Name</th>
        <th>Blogpost Name</th>
        <th>Post Date</th>
   
    </tr>
    {% for x in mymembers %}
    <tr align="center">
     
        <td><a href="{% url 'members:authordetail' %}">{{ x.User }}</a></td>
        <td>{{ x.Blogpost_name }}</td> 
        <td>{{ x.Post_date }}</td>
       
    </tr>
    {% endfor %}
</table>
<div class="pagination">
    <span class="step-links">
        {% if mymembers.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ mymembers.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ mymembers.number }} of {{ mymembers.paginator.num_pages }}.
        </span>

        {% if mymembers.has_next %}
            <a href="?page={{ mymembers.next_page_number }}">next</a>
            <a href="?page={{ mymembers.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</form> 
</body>
</head>
</html>    

members/templates/home.html
<h1>Welcome to Home page</h1>

members/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <body>
           
            <button style="font-size : 20px; width: 10%; height: 30px;"><a href="{% url 'members:signup' %}">SignUp</a></button>
            <button style="font-size : 20px; width: 10%; height: 30px;"><a href="{% url 'members:login' %}">LogIn</a></button>

            <h3><a href="{% url 'members:home' %}">Home</a></h3>  
            <h3><a href="{% url 'members:blogpost' %}">List of All BlogPost:</a></h3>
            <h3><a href="author/">Author Detail</a></h3>
            <h3><a href="blogpostdetail/">BlogPost Deatil</a>
            <h3><a href="bloggers/">Bloggers</a></h3>
        </body>
    </head>
</html>    

members/templates/login.html
<!DOCTYPE html>    
<html>    
<head>          
</head>    
<body>    
    <h2>Login Page</h2><br>  
    <form  method="POST" action="{% url 'members:login' %}">    
    {% csrf_token %}  
        <label><b>User Name </b>
        </label>    
        <input type="text" name="User_name" id="User_name" placeholder="Username">    
        <br><br>    
        <label><b>Password </b>    
        </label>    
        <input type="Password" name="User_pwd" id="User_pwd" placeholder="Password">    
        <br><br>    
        <input type="submit" name="log" id="log" value="Log In Here">  
        <p>{{message}}</p>    
        <br><br>    
    </form>       
</body>    
</html>            
       

members/templates/signup.html
<!DOCTYPE html>
<html>
<head>
<body>
    <form action ="{% url 'members:signup' %}" method="POST" enctype="multipart/form-data">
        <fieldset>
            <legend>Form</legend>
            {% csrf_token %}
            <table>{{ form }}</table>
            <input type="submit" name="save" value="Submit">
        </fieldset>
        
    </form>
</body>    
</head>    
</html>    